title: Jaroslaw Kitkowski # your name (or website title) here
logo: "/images/kitkowski.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UI/UX Designer 
  <br><br>
  Passionate about great UX design. 
  <br><br>
  <a href="https://www.linkedin.com/in/jaroslaw-kitkowski/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://kitkowski.github.io/pdf/Jaroslaw_UX_Designer.pdf/">Check my CV</a> 
   <br><br>
  <a href="https://kitkowski.github.io/pdf/Jaroslaw_UX_Designer-1.pdf/">Alternative CV</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
